### ISSUE TITLE
Fails to run on linux: Illegal storage access.

### ISSUE THREAD

**Issue by radgeRayden** [floooh/sokol-nim#5]
I know it's said to be untested on linux, but I figured I'd file an issue anyway to let you know and hopefully this can get fixed (or I might figure it out sometime).
This is the traceback, I tried running `cube` but all examples I tested have the same issue.

```
Traceback (most recent call last)
cube.nim(22)             cube
gfx.nim(547)             setup
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

line 22 is `sg.setup`.

**Comment by floooh** [comment]
Thanks for taking the time to file the bug report :)! I need to get back to the nim bindings at one point, because a lot has happened since then. Here's what I have in mind:

- include copies of the sokol headers directly, instead of as a git submodule
- add bindings at least for sokol_app.h, so glad.c/.h could be dropped, and it would be possible to easier to build cross-platform applications that use D3D11 and Metal (especially important for MacOS)
- update the sokol_gfx.h bindings to the latest sokol API

**Comment by geotre** [comment]
Any news on linux support? I get the same error as above

**Comment by floooh** [comment]
nope, haven't looked at it yet, sorry

**Comment by melMass** [comment]
Did you made the bindings all by hand ?

**Comment by floooh** [comment]
> Did you made the bindings all by hand ?

I don't remember :D It's definitely not completely generated though since I had to add a few helpers. Maybe converted with a tool and then "touched up".

**Comment by floooh** [comment]
Apparently this is fixed not with https://github.com/floooh/sokol-nim/pull/8 (haven't tested myself yet on Linux though)
